# Generated by Django 5.1.1 on 2025-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_product_name_product_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("desc", models.CharField(default="", max_length=500)),
                ("phone", models.IntegerField(default=0)),
            ],
        ),
    ]
